---
# tasks file for prometheus_grafana
- name: test connection
  ping:

- name: install require packages in amazon linux
  yum: 
   name: ['git', 'make', 'gcc', 'wget','telnet','gzip']
   state: latest
  when: ansible_os_family == "RedHat"
  
- name: install require packages in ubuntu
  apt: 
   name: ['git', 'make', 'gcc', 'wget','telnet','gzip']
   state: latest
   update_cache: yes
  when: ansible_os_family == "Debian"

- name: create group
  group:
   name: prometheus
   state: present

- name: create user
  user:
   name: prometheus
   group: prometheus
   createhome: no
   system: yes
   state: present

- name: create opt directory for prometheus
  file:
   path: /opt/prometheus
   state: directory

- name: download node exporter
  get_url:
   url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
   dest: /opt/prometheus

- name: unarchive node exporter
  unarchive:
   remote_src: yes
   src: /opt/prometheus/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
   dest: /opt/prometheus

- name: create symlink to node exporter
  file:
   path: /usr/bin/node_exporter
   state: link
   src: /opt/prometheus/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
   
- name: install unit file to systemd
  template:
   src: node_exporter.service
   dest: /etc/systemd/system/node_exporter.service

- name: configure systemd to use service
  systemd:
   daemon_reload: yes
   enabled: yes
   state: started
   name: node_exporter.service


- name: update and install prometheus
  apt:
   name: prometheus
   state: latest
   update_cache: yes
   cache_valid_time: 3600

- name: prometheus args
  template:
   src: prometheus.j2
   dest: /etc/default/prometheus
   mode: 0644
   owner: root
   group: root
  notify: restart_prometheus

- name: prometheus configuration file
  template:
   src: prometheus.yml.j2
   dest: "{{ prometheus_dir_configuration }}/prometheus.yml"
   mode: 0755
   owner: prometheus
   group: prometheus
  notify: restart_prometheus
  
- name: start prometheus
  systemd:
   name: prometheus
   state: started
   enabled: yes